### ISSUE TITLE
Installation on Mac 

### ISSUE THREAD

**Issue by MJCliffe** [disorderedmaterials/Gudrun#19]
Hi - running into an SZIP error when running Cmake on Mac (12.6.1).

`CMake Error at CMakeLists.txt:73 (find_package):
  By not providing "FindSZIP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SZIP", but
  CMake did not find one.

  Could not find a package configuration file provided by "SZIP" with any of
  the following names:

    SZIPConfig.cmake
    szip-config.cmake

  Add the installation prefix of "SZIP" to CMAKE_PREFIX_PATH or set
  "SZIP_DIR" to a directory containing one of the above files.  If "SZIP"
  provides a separate development package or SDK, be sure it has been
  installed.`

**Comment by rhinoella** [comment]
When you run the cmake command, run it using the option `BUILD_SZIP:bool=true`:

`cmake ../ -G Ninja -DCMAKE_Fortran_COMPILER:string="gfortran-11" -DBUILD_SZIP:bool=true -DCMAKE_Fortran_FLAGS:string="-cpp"`

This tells CMake to build SZIP instead of looking to find a local installation.
