### ISSUE TITLE
hdf5 libraries not found on CentOS 7

### ISSUE THREAD

**Issue by franzlang** [disorderedmaterials/Gudrun#6]
Trying to compile Gudrun on CentOS 7 leads to the following error:
```
/Gudrun/src/neutron/libGudrunN/datasetlist.f90:10/8:
use HDF5
1
Fatal Error: Can't open module file 'hdf5.mod' for reading at (1): No such file or directory
```
The `hdf5` and `hdf5-devel` modules have both been installed and the file `hdf5.mod` is actually present in location `/usr/lib64/gfortran/modules/hdf5.mod`. Even copying it to other standard locations like `/usr/local/hdf5/include/` did not resolve the problem. In addition, using the `HDF5_DIR` as suggested in [CMakeLists.txt](https://github.com/disorderedmaterials/Gudrun/blob/bf2c910b1f525c1c961c8439ac50311da7149567/CMakeLists.txt#L14) did not help either (although I might have been using it wrong).

**Comment by trisyoungs** [comment]
Not sure why this happens either - it builds without this error on OpenSuSE (15.3) so I can only assume it's a subtlety with how the Fortran90 module path is set for the HDF5 package on CentOS.

As a temporary workaround the `hdf5.mod` file can be copied into our `src` dir where it should get picked up correctly.
